<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Bienvenido</title>
	<link rel="stylesheet" href="<?php echo APP_URL;?>views/layouts/default/css/normalize.min.css">
	<link rel="stylesheet" href="<?php echo APP_URL;?>views/layouts/default/css/bootstrap.min.css">
	<link rel="stylesheet" href="<?php echo APP_URL;?>views/layouts/default/css/main.css">
	<script src="<?php echo APP_URL; ?> views/layouts/default/js/vendor/modernizr-2.8.3.min.js"></script>
</head>
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="<?php echo APP_URL;?>/views/layouts/default/js/vendor/jquery-1.11.2.min.js"><\/script>')</script>
    <script src="<?php echo APP_URL;?>views/layouts/default/js/vendor/bootstrap.min.js"></script>
    <script src="<?php echo APP_URL;?>views/layouts/default/js/plugins.js"></script>
    <script src="<?php echo APP_URL;?>views/layouts/default/js/main.js"></script>

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X','auto');ga('send','pageview');
        </script>
<body>
<div class="container">
		<div class="row">
			<header>
				<div class="row-md-6"><h1>Money traking</h1></div>
				<div class="row-md-6"><h1><?php if (isset($_SESSION["username"])): ?>
									<h4> Hola <?php echo $_SESSION['username'] ;?></h4>
									</h1>
									<?php endif; ?>
				</div>
			</header>
		</div>
		<div class="row">
			<div class="col-md-12">
				<nav>
					<ul class="list-inline">
						<li><a href="<?php echo APP_URL; ?>">Home</a></li>
						<li><a href="<?php echo APP_URL; ?>pages">Pages</a></li>
						<li><a href="<?php echo APP_URL; ?>users">Users</a></li>
						<li><a href="<?php echo APP_URL; ?>categories">Categories</a></li>
						<li><a href="<?php echo APP_URL; ?>transactions">Transactions</a></li>
						<li><a href="<?php echo APP_URL; ?>accounts">Accounts</a></li>
						<li><a href="<?php echo APP_URL; ?>users/logout">Logout</a></li>
					</ul>
				</nav>
			</div>
		</div>